### ISSUE TITLE
Activity implementation (Session 1)

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#10]

**Comment by Sof1a** [comment]
Actividad 6 de febrero de 2020

Usaremos el juego “Uno” como herramienta para reconocer y decir cualidades tanto personales como de los demás participantes, según los `poderes` designados de la siguiente manera:

Cartas 1 y 5: decir una cualidad de la persona que esté al lado (según la dirección que lleve el juego), y cada que salga alguna de esas cartas se dirá la cualidad de la persona que sigue (no se repite persona).
Cartas 3 y 7: decir una cualidad propia.
Cartas 4 y 6: realizar una pregunta al azar.

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
