### ISSUE TITLE
Improve the activity to get better information

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#11]

**Comment by Sof1a** [comment]
Después de realizada la actividad (version 1) surgieron algunas mejoras que se llevarán a cabo el 13 de febrero:

Para las preguntas se debe dar cierto parámetro como por ejemplo preguntas que sean personales, sin propasarse, algo más encaminado a lo que se solicita en las otras cartas, no tan a la imaginación de los demás.
No se pueden clonar las cartas.
Repartir las cartas de tal modo que a cada uno le quede mínimo una de las cartas con poder.
Asignarle poder a las cartas 2 y 8.

Por ende las asignaciones de poder variarán y se tendrán en cuenta las cartas 2 y 8 para esta nueva actividad

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
