### ISSUE TITLE
Activity implementation (Session 2)

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#12]

**Comment by Sof1a** [comment]
Actividad 13 de febrero

Cartas 1 y 3: decir un adjetivo descriptivo de la persona que esté al lado (según la dirección que lleve el juego), y cada que salga alguna de esas cartas se dirá el adjetivo de la persona que sigue (no se repite persona).
Cartas 4 y 7: decir un adjetivo descriptivo de sí mismo.
Cartas 2 y 5: Elegir un jugador y hacerle una pregunta sobre algún aspecto de su personalidad.
Cartas 6 y 8: decirle algo agradable a alguien elegido por quienes dirigen la actividad.

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
