### ISSUE TITLE
Research about the player engagement model

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#18]
![image](https://user-images.githubusercontent.com/28972480/78219037-65c2ed00-7484-11ea-929f-4a32eaf06ac8.png)

Colaborativo/Competitivo: La aplicación tendrá un enfoque competitivo, ya que dependiendo del puntaje obtenido semanalmente, ubicará a los equipos y a los miembros en tablas de clasificación.
Intrínseco/Extrínseco: La aplicación tendrá un enfoque a la motivación intrínseca y extrínseca, puesto que el usuario hará uso de la app para motivar el uso de la herramienta de gestión de proyectos, mientras que al mismo tiempo recibirá puntos e insignias según su su progreso.  
Multiplayer/1Player: La aplicación será de 1 Player, pues es será únicamente utilizada por el coordinador del área de juegos, sin interacción alguna con otros jugadores. 
Campaña/Interminable: Tendrá un enfoque orientado a interminable, ya que el fin de la aplicación es mejorar el nivel de uso de la aplicación de gestión de proyectos y ayudar a llevar un mayor orden en las actividades asignadas.
Emergente/Escrito: El resultado que dará el uso de la aplicación no es conocido, por lo tanto es emergente, pues todo depende absolutamente de los usuarios y del uso consciente de esta herramienta.

**Comment by Sof1a** [comment]
![Captura- revisión issues SoLe2](https://user-images.githubusercontent.com/50718855/80745166-7bf4b500-8ae5-11ea-8ea1-02db002f6a2a.PNG)
