### ISSUE TITLE
Player engagement model definition

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#20]
Result:

![Bar Graph - Presentation](https://user-images.githubusercontent.com/28972480/79409639-0d035200-7f64-11ea-89af-47123d73f41e.png)

**Comment by Sof1a** [comment]
![Captura- revisión issues SoLe3](https://user-images.githubusercontent.com/50718855/80745313-b8281580-8ae5-11ea-8b01-809430bd19ca.PNG)
