### ISSUE TITLE
Gamification elements survey design

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#22]
Design of a survey to know the perspective of the team members about the gamification elements to be implemented in the app.
https://forms.gle/mDUhnSQbs2pEXXHa7

**Comment by Sof1a** [comment]
![Captura- revisión issues SoLe](https://user-images.githubusercontent.com/50718855/80744788-d4778280-8ae4-11ea-9680-641ceb31759d.PNG)
