### ISSUE TITLE
Proposed solution definition

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#3]
Definition of the proposed solution at the document.

**Comment by Sof1a** [comment]
se propone el desarrollo de una estrategia de gamificación implementada mediante una aplicación web la cual permitirá realizar un seguimiento adecuado al avance de los integrantes en los proyectos que estén trabajando así como incentivarlos a hacer uso de las herramientas de gestión de proyectos.

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
