### ISSUE TITLE
Scope definition

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#4]
Alcance
Como idea, la aplicación es bastante robusta, tiene bastantes funcionalidades a desarrollar para que pueda ser completada a primera instancia, por eso y para el desarrollo del proyecto, se plantea un alcance de objetivos mínimos para que sea funcional y pueda ser evaluada y probada. Por consiguiente queda abierta a futuros desarrollos y mejoras.

La aplicación permitirá: 
Conocer el estado general un determinado proyecto, sus historias de usuario y errores.
Ver el rendimiento que ha tenido cada integrante en los proyectos que participa.
Conocer si las historias de usuario y errores fueron solucionados en el tiempo establecido.

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
