### ISSUE TITLE
Metric definition

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#5]
Métricas
Resultados esperados:
A través de la aplicación y su estrategia de gamificación fomentar la creación, asignación y gestión de historias de usuario, tareas e issues.
Ayudar a conocer más fácilmente el avance de los proyectos mediante una interfaz sencilla y amigable.
Validar que un sprint se cerró correctamente (En el tiempo establecido).

Métricas de los resultados:
Que al menos el 80% de los participantes, tengan un resultado progresivo de mejora, que se medirá con la creación, estimación, asignación y gestión de las historias de usuario e issues.
Que al menos el 50% se sienta satisfecho y siga usando la aplicación o los hábitos adquiridos mediante esta aplicación.
Cerrar correctamente el 80% de los sprints.

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
