### ISSUE TITLE
Survey design for people creation

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#7]
Survey was designed and implemented already.

**Comment by DianaKToro** [comment]
It's not clear if the task has been completed. Please add description and evidence of results

**Comment by Sof1a** [comment]
![image](https://user-images.githubusercontent.com/50718855/83171865-5656cd80-a0dc-11ea-8d72-9687c3c9cc3e.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
