### ISSUE TITLE
Activity design for people creation

### ISSUE THREAD

**Issue by LeidyJr** [MCV-Univalle/SoLe#8]
Activity was already done.

**Comment by DianaKToro** [comment]
It's not clear if the task has been completed. Please add description and evidence of results

**Comment by Sof1a** [comment]
![image](https://user-images.githubusercontent.com/50718855/83173736-f877b500-a0de-11ea-8a38-092e90c42a99.png)

**Comment by Sof1a** [comment]
![image](https://user-images.githubusercontent.com/50718855/83174506-1c87c600-a0e0-11ea-8a1d-a42b98bc01f2.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
